<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>phalcon</title>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #35394a;
            font-size: 18px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
</head>
<body>
<h1>Phalcon</h1>

<div>a high performance framework for PHP</div>

<p>Try <a href="https://github.com/xxtime/phalcon-module">Phalcon Framework</a>
</body>
</html>